### ISSUE TITLE
Options is null when saving/publishing a node

### ISSUE THREAD

**Issue by mcl-sz** [bielu/bielu.examine.providers#8] opened 2024-03-12 10:29 UTC
When a node is saved or published, an error occures.

The error is occures because the options in 
https://github.com/bielu/bielu.examine.providers/blob/4a5aaa98d8c4fbf9017010e6f428d8636a0e2094/src/Bielu.Examine.ElasticSearch/Queries/ElasticSearchQuery.cs#L70 is null.

I've tried to give the options default values 

```
                .Size(options?.Take ?? 200)
                .From(options?.Skip ?? 0)
```
then this error is gone/bypassed but the next problem is that the query cannot be converted to a searchresult

![afbeelding](https://github.com/bielu/bielu.examine.providers/assets/18614643/0f9d6a51-0946-4ced-87a8-eaa644c7ef46)

**Comment by bielu** [comment] 2024-03-12 12:00
will have a look this afternoon :)

**Comment by bielu** [comment] 2024-03-12 21:02
I was able to reproduce issue with options, but can't reproduce issue with search result, can you maybe setup example project with this issue?

**Comment by mcl-sz** [comment] 2024-03-13 09:05
Hi @bielu , I had created a demo project to demonstrate where things went wrong, but you guessed it: no problems in the demo :) 
But then I discovered the difference: in my regular project the Delivery Api is enabled. When I enable the Delivery API in my demo project, the above error occurs. So the error seems to only occur when the Delivery API is enabled.

**Comment by bielu** [comment] 2024-03-13 09:09
ohh so it might be the case of delivery api, which I didnt test yet

**Comment by mcl-sz** [comment] 2024-03-13 09:13
I tested some more, but the indexes are not updated when the content is changed.
For example, I named the "Home" node "Home2" but the indexes only show "Home". So even though no error message occurs, saving and publishing does not seem to function properly yet.

**Comment by bielu** [comment] 2024-03-13 10:06
okay will invesitgate it!

**Comment by bielu** [comment] 2024-03-13 18:10
Hey @mcl-sz I hope this is not huge blocker as will try address it over this weekend. However i hope to get this pr (https://github.com/bielu/bielu.examine.providers/pull/9) finished first so I am done with breaking changes for providers :) 
If I will not get to state where I want be on sunday I will address this issue seperately.

**Comment by bielu** [comment] 2024-03-17 15:35
I am working on this issue today! it will be released as part of this pr:
https://github.com/bielu/bielu.examine.providers/pull/10

**Comment by bielu** [comment] 2024-03-17 18:43
hey @mcl-sz, 
Latest package [1.0.0-beta.638462976255970049](https://www.nuget.org/packages/Bielu.Examine.Core/1.0.0-beta.638462976255970049) should resolve this issue, please follow new information docs how to use :) 
please let me know if I missed something in docs!

**Comment by bielu** [comment] 2024-04-01 14:18
hey @mcl-sz did you had chance to test it on your end?

**Comment by mcl-sz** [comment] 2024-04-02 11:17
Hi @bielu, apologies for my late response and thanks again for all the work you put into it! 
Publishing/depublishing now works completely fine!

I'm still having a few problems searching in the back office. Sorry! I will create new issues for this if you agree.

**Comment by bielu** [comment] 2024-04-02 12:16
@mcl-sz yeah please! lets see what else is wrong

**Closed as completed by bielu** 2024-04-02 12:16 UTC
